### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by SuperOP535** [SuperOP535/Nogar#1]
### To-do list
- [ ] Client
  - [x] Send messages to the chat
  - [x] Recieve messages from the chat
  - [x] Join the game with a specified nickname
  - [x] Do basic actions like eject and split
  - [ ] Proxy support
    - [ ] Checking proxies
      - [ ] HTTP & HTTPS
      - [ ] SOCKS4
      - [ ] SOCKS5
      - [ ] Ensure that the proxy is anonymous
    - [ ] HTTP & HTTPS
    - [ ] SOCKS4
    - [ ] SOCKS5
  - [ ] Multi-protocol
    - [x] Protocol 4
    - [ ] Protocol 6
  - [ ] Move to a specified position
  - [ ] Player death event
- [ ] Server
  - [x] Fetch the leaderboard values
  - [x] Fetch player position
  - [x] Fetch player score
- [ ] Other
  - [ ] Provide an easy-to-use API
